name: "Trigger Pipedream Workflow"
author: "hugoalh"
description: "Trigger Pipedream workflow via SDK or webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  method:
    description: "{string} Method to trigger."
    required: false
  payload:
    description: "{object} JSON/YAML/YML payload."
    required: false
    default: "{}"
runs:
  using: "node16"
  main: "../nodejs-loader.js"
branding:
  icon: "zap"
  color: "green"
