name: "Trigger Pipedream Workflow"
author: "hugoalh"
description: "Trigger Pipedream workflow via SDK or webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  method:
    description: "{string} Method to trigger."
    required: false
  payload:
    description: "{object} JSON/YAML/YML payload."
    required: false
    default: "{}"
outputs:
  response:
    description: "{string} Response content."
  status_code:
    description: "{number} Request status code."
  status_ok:
    description: "{boolean} Whether the request was successful."
  status_text:
    description: "{string} Request status text."
runs:
  using: "node16"
  main: "dist/main.js"
branding:
  icon: "zap"
  color: "green"
