name: "Trigger Pipedream Workflow"
author: "hugoalh"
description: "Trigger Pipedream workflow via SDK or webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  method:
    description: "{string} Method to trigger."
    required: false
  payload:
    description: "{object} JSON/YAML/YML payload."
    required: false
    default: "{}"
runs:
  using: "docker"
  image: "docker://ghcr.io/hugoalh/trigger-pipedream-workflow-ghaction:2.2.1"
branding:
  icon: "zap"
  color: "green"
