name: "Send To Pipedream"
author: "hugoalh"
description: "Send data to Pipedream via SDK."
inputs:
  key:
    description: "{string.secret} Pipedream SDK key."
    required: true
  variable_join:
    description: "{string} Variable join if the variable list has depth."
    required: false
    default: "_"
  variable_list_external:
    description: "{object.json} External variable list that will use in the data."
    required: false
  variable_prefix:
    description: "{string} Variable prefix."
    required: false
    default: "%"
  variable_suffix:
    description: "{string} Variable suffix."
    required: false
    default: "%"
  payload:
    description: "{(string|object.json)} Payload that need to send to Pipedream."
    required: true
  github_token:
    description: "{string.secret} GitHub personal access token."
    required: false
    default: "${{github.token}}"
runs:
  using: "node12"
  pre: "setup.js"
  main: "main.js"
branding:
  icon: "send"
  color: "blue"
