name: "Trigger Pipedream Workflow"
author: "hugoalh"
description: "Trigger Pipedream workflow via SDK or webhook."
inputs:
  key:
    description: "{string} Key."
    required: true
  payload:
    description: "{object} JSON payload."
    required: false
    default: "{}"
runs:
  using: "composite"
  steps:
    - name: "Modify PowerShell Repository"
      id: "modify-powershell-repository"
      run: |
        Write-Host -Object "::set-output name=installation-policy::$((Get-PSRepository -Name 'PSGallery').InstallationPolicy)"
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted' -Verbose
      shell: "pwsh"
    - name: "Setup PowerShellGet"
      run: |
        Install-Module -Name 'PowerShellGet' -MinimumVersion '2.2.5' -Scope 'AllUsers' -AcceptLicense -Verbose
      shell: "pwsh"
    - name: "Update PowerShell Modules"
      run: |
        Update-Module -Scope 'AllUsers' -AcceptLicense -Verbose
      shell: "pwsh"
    - name: "Setup Action's Dependencies"
      run: |
        Install-Module -Name 'hugoalh.GitHubActionsToolkit' -MinimumVersion '0.5.0' -Scope 'CurrentUser' -AcceptLicense -Verbose
      shell: "pwsh"
    - name: "Execute Main Action"
      run: |
        ${{github.action_path}}/../main.ps1 -Key '${{inputs.key}}' -Payload '${{inputs.payload}}'
      shell: "pwsh"
    - name: "Revert Modify PowerShell Repository"
      if: "${{steps.modify-powershell-repository.outcome == 'success' && always()}}"
      run: |
        Set-PSRepository -Name 'PSGallery' -InstallationPolicy '${{steps.modify-powershell-repository.outputs.installation-policy}}'
      shell: "pwsh"
branding:
  icon: "zap"
  color: "green"
