# content:
# username:
# avatar_url:
tts: false
embeds:
  - title: "Trigger Pipedream Workflow (GitHub Action Edition)"
    description: "Version %payload.release.name% (%payload.release.tag_name%) is released and available on:"
    # url:
    color: "16,116,231"
    # footer:
      # text:
      # icon_url:
    image:
      url: "https://i.imgur.com/O95tqRP.png"
    thumbnail:
      url: "https://i.imgur.com/knmLbFg.png"
    # video:
      # url:
    # author:
      # name:
      # url:
      # icon_url:
    fields:
      - name: "GitHub (& Changelog)"
        value: "%payload.release.html_url%"
        inline: false
      - name: "GitHub Marketplace"
        value: "https://github.com/marketplace/actions/trigger-pipedream-workflow"
        inline: false
      - name: "Repository"
        value: "%payload.repository.html_url%"
        inline: false
